default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: collabfield_development
  username: muhammad

test:
  <<: *default
  database: collabfield_test

production:
  <<: *default
  database: collabfield_production
  username: collabfield
  password: <%= ENV['COLLABFIELD_DATABASE_PASSWORD'] %>
